version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: pry
    versions:
    - 0.13.1
    - 0.14.0
  - dependency-name: timecop
    versions:
    - 0.9.2
    - 0.9.3
